name: is_it_safe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.1.2
  rxdart: ^0.27.2
  dio: ^4.0.0
  intl_utils: ^2.4.1
  google_fonts: ^2.3.1
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.8
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^0.22.0
  plugin_platform_interface: ^2.0.2
  provider: ^6.0.1
  mask_text_input_formatter: ^2.0.0
  mockito: ^5.0.16
  simple_animations: ^4.0.1
  platform: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  modular_test: ^1.0.1+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/app/profile_pictures/
    - images/app/on_boarding/
    - images/app/profile_pictures/
    - images/app/home/
    - images/app/home/drawer/
    - images/app/profile_pictures/placeholder/
    - images/icons/
    - images/app/search_pictures/placeholder/




flutter_intl:
  enabled: true
  main_locale: pt