name: is_it_safe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  #Funcionalidades do Sistema
  flutter_modular: ^5.0.3
  provider: ^6.0.3
  plugin_platform_interface: ^2.1.2
  platform: ^3.1.0
  logger: ^1.1.0
  meta: ^1.7.0

  #Requisições HTTP
  dio: ^4.0.6
  jwt_decode: ^0.3.1

  #Internacionalização
  intl_utils: ^2.4.1

  #Estilização
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  mask_text_input_formatter: ^2.0.0

  #Componentes
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.4
  simple_animations: ^4.0.1

  #Armazenamento
  shared_preferences: ^2.0.15

  #Testes
  mocktail: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  modular_test: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - test/src/service/api/modules/auth/mocks/
    - images/logo/logo.png
    - images/
    - images/modules/
    - images/modules/auth/
    - images/modules/auth/
    - images/modules/auth/profile_pictures/
    - images/modules/auth/profile_pictures/placeholder/
    - images/modules/home/
    - images/modules/core/empty/
    - images/modules/core/icons/
    - images/modules/core/placeholder/
    - images/modules/review/
 
    

flutter_intl:
  enabled: true
  main_locale: pt